AWSTemplateFormatVersion: '2010-09-09'
Description: Create CodeBuild project that builds Docker image from S3 ZIP source and pushes to ECR.

Parameters:
  ProjectName:
    Type: String
    Default: m365-get-user-container-build
    Description: Name of the CodeBuild project.
  SourceBucket:
    Type: String
    Description: S3 bucket containing the source ZIP.
  SourceKey:
    Type: String
    Description: S3 key (object path) of the source ZIP.
  ImageRepoName:
    Type: String
    Default: m365-get-user-container
    Description: ECR repository name to push images to.
  CreateECRRepository:
    Type: String
    AllowedValues: ['true','false']
    Default: 'true'
    Description: Whether to create the ECR repository if it does not exist.
  EnvironmentImage:
    Type: String
    Default: aws/codebuild/standard:7.0
    Description: CodeBuild environment image.
  ComputeType:
    Type: String
    AllowedValues:
      - BUILD_GENERAL1_SMALL
      - BUILD_GENERAL1_MEDIUM
      - BUILD_GENERAL1_LARGE
    Default: BUILD_GENERAL1_SMALL
    Description: CodeBuild compute type.
  AwsDefaultRegion:
    Type: String
    Default: ap-northeast-1
    Description: Default AWS region used inside the build.

Conditions:
  CreateECR: !Equals [ !Ref CreateECRRepository, 'true' ]

Resources:
  CodeBuildServiceRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub "codebuild-${ProjectName}-role"
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: codebuild.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/CloudWatchLogsFullAccess
        - arn:aws:iam::aws:policy/AmazonS3ReadOnlyAccess
        - arn:aws:iam::aws:policy/AmazonEC2ContainerRegistryPowerUser

  ECRRepository:
    Type: AWS::ECR::Repository
    Condition: CreateECR
    Properties:
      RepositoryName: !Ref ImageRepoName

  CodeBuildProject:
    Type: AWS::CodeBuild::Project
    Properties:
      Name: !Ref ProjectName
      ServiceRole: !GetAtt CodeBuildServiceRole.Arn
      Artifacts:
        Type: NO_ARTIFACTS
      Source:
        Type: S3
        Location: !Sub "${SourceBucket}/${SourceKey}"
      Environment:
        Type: LINUX_CONTAINER
        Image: !Ref EnvironmentImage
        ComputeType: !Ref ComputeType
        PrivilegedMode: true
        EnvironmentVariables:
          - Name: AWS_DEFAULT_REGION
            Type: PLAINTEXT
            Value: !Ref AwsDefaultRegion
          - Name: IMAGE_REPO_NAME
            Type: PLAINTEXT
            Value: !Ref ImageRepoName
          - Name: IMAGE_TAG
            Type: PLAINTEXT
            Value: ""
          - Name: DOCKERFILE
            Type: PLAINTEXT
            Value: "Dockerfile_al2023"

Outputs:
  CodeBuildProjectName:
    Description: Created CodeBuild project name
    Value: !Ref CodeBuildProject
  CodeBuildServiceRoleArn:
    Description: IAM role ARN used by CodeBuild
    Value: !GetAtt CodeBuildServiceRole.Arn
  ECRRepositoryName:
    Condition: CreateECR
    Description: ECR repository name
    Value: !Ref ECRRepository
