AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: aws-lambda-powershell-getuser-runtime

Parameters:
  LayerName:
    Type: String
    Default: "SimPwshRuntimeLayer"
  LayerVersion:
    Type: Number
    Default: 1 

Resources:
  ##########################################################################
  # IAM ロール（Lambda用）                                                  #
  ##########################################################################
  LambdaM365GetUserRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Policies:
        - PolicyName: M365GetUserSSMPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - ssm:GetParameter
                  - kms:Decrypt
                Resource:
                  - Fn::Sub: arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/m365/*
              - Effect: Allow
                Action: lambda:InvokeFunction
                Resource: 
                  - Fn::Sub: arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:M365Auth
                  - Fn::Sub: arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:M365CollectS3Export

  ##########################################################################
  # Lambda関数（M365ユーザ情報取得関数）                                       
  ##########################################################################
  M365GetUserFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: M365GetUser
      PackageType: Zip
      Handler: M365GetUser.ps1::M365GetUser
      Runtime: provided.al2
      CodeUri: ./
      Layers:
        - Fn::Sub: "arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:layer:${LayerName}:${LayerVersion}"
      Timeout: 900
      MemorySize: 512
      Role: !GetAtt LambdaM365GetUserRole.Arn
      Architectures:
        - arm64
      Environment:
        Variables: 
          POWERSHELL_RUNTIME_VERBOSE: TRUE
